// <auto-generated />
using Catalog.PersistenceDataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Catalog.PersistenceDataBase.Migrations
{
    [DbContext(typeof(AplicationDBContext))]
    [Migration("20220417031828_initialize")]
    partial class initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Catalog")
                .HasAnnotation("ProductVersion", "3.1.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CatologDomain.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescriptionProduct")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("NameProduct")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            DescriptionProduct = "Description 1",
                            NameProduct = "Product1",
                            Price = 238
                        },
                        new
                        {
                            ProductId = 2,
                            DescriptionProduct = "Description 2",
                            NameProduct = "Product2",
                            Price = 226
                        },
                        new
                        {
                            ProductId = 3,
                            DescriptionProduct = "Description 3",
                            NameProduct = "Product3",
                            Price = 37
                        },
                        new
                        {
                            ProductId = 4,
                            DescriptionProduct = "Description 4",
                            NameProduct = "Product4",
                            Price = 140
                        },
                        new
                        {
                            ProductId = 5,
                            DescriptionProduct = "Description 5",
                            NameProduct = "Product5",
                            Price = 39
                        },
                        new
                        {
                            ProductId = 6,
                            DescriptionProduct = "Description 6",
                            NameProduct = "Product6",
                            Price = 229
                        },
                        new
                        {
                            ProductId = 7,
                            DescriptionProduct = "Description 7",
                            NameProduct = "Product7",
                            Price = 48
                        },
                        new
                        {
                            ProductId = 8,
                            DescriptionProduct = "Description 8",
                            NameProduct = "Product8",
                            Price = 472
                        },
                        new
                        {
                            ProductId = 9,
                            DescriptionProduct = "Description 9",
                            NameProduct = "Product9",
                            Price = 294
                        },
                        new
                        {
                            ProductId = 10,
                            DescriptionProduct = "Description 10",
                            NameProduct = "Product10",
                            Price = 37
                        },
                        new
                        {
                            ProductId = 11,
                            DescriptionProduct = "Description 11",
                            NameProduct = "Product11",
                            Price = 53
                        },
                        new
                        {
                            ProductId = 12,
                            DescriptionProduct = "Description 12",
                            NameProduct = "Product12",
                            Price = 64
                        },
                        new
                        {
                            ProductId = 13,
                            DescriptionProduct = "Description 13",
                            NameProduct = "Product13",
                            Price = 314
                        },
                        new
                        {
                            ProductId = 14,
                            DescriptionProduct = "Description 14",
                            NameProduct = "Product14",
                            Price = 234
                        },
                        new
                        {
                            ProductId = 15,
                            DescriptionProduct = "Description 15",
                            NameProduct = "Product15",
                            Price = 414
                        },
                        new
                        {
                            ProductId = 16,
                            DescriptionProduct = "Description 16",
                            NameProduct = "Product16",
                            Price = 81
                        },
                        new
                        {
                            ProductId = 17,
                            DescriptionProduct = "Description 17",
                            NameProduct = "Product17",
                            Price = 375
                        },
                        new
                        {
                            ProductId = 18,
                            DescriptionProduct = "Description 18",
                            NameProduct = "Product18",
                            Price = 240
                        },
                        new
                        {
                            ProductId = 19,
                            DescriptionProduct = "Description 19",
                            NameProduct = "Product19",
                            Price = 363
                        },
                        new
                        {
                            ProductId = 20,
                            DescriptionProduct = "Description 20",
                            NameProduct = "Product20",
                            Price = 262
                        },
                        new
                        {
                            ProductId = 21,
                            DescriptionProduct = "Description 21",
                            NameProduct = "Product21",
                            Price = 241
                        },
                        new
                        {
                            ProductId = 22,
                            DescriptionProduct = "Description 22",
                            NameProduct = "Product22",
                            Price = 189
                        },
                        new
                        {
                            ProductId = 23,
                            DescriptionProduct = "Description 23",
                            NameProduct = "Product23",
                            Price = 454
                        },
                        new
                        {
                            ProductId = 24,
                            DescriptionProduct = "Description 24",
                            NameProduct = "Product24",
                            Price = 157
                        },
                        new
                        {
                            ProductId = 25,
                            DescriptionProduct = "Description 25",
                            NameProduct = "Product25",
                            Price = 198
                        },
                        new
                        {
                            ProductId = 26,
                            DescriptionProduct = "Description 26",
                            NameProduct = "Product26",
                            Price = 425
                        },
                        new
                        {
                            ProductId = 27,
                            DescriptionProduct = "Description 27",
                            NameProduct = "Product27",
                            Price = 345
                        },
                        new
                        {
                            ProductId = 28,
                            DescriptionProduct = "Description 28",
                            NameProduct = "Product28",
                            Price = 64
                        },
                        new
                        {
                            ProductId = 29,
                            DescriptionProduct = "Description 29",
                            NameProduct = "Product29",
                            Price = 427
                        },
                        new
                        {
                            ProductId = 30,
                            DescriptionProduct = "Description 30",
                            NameProduct = "Product30",
                            Price = 181
                        },
                        new
                        {
                            ProductId = 31,
                            DescriptionProduct = "Description 31",
                            NameProduct = "Product31",
                            Price = 458
                        },
                        new
                        {
                            ProductId = 32,
                            DescriptionProduct = "Description 32",
                            NameProduct = "Product32",
                            Price = 350
                        },
                        new
                        {
                            ProductId = 33,
                            DescriptionProduct = "Description 33",
                            NameProduct = "Product33",
                            Price = 13
                        },
                        new
                        {
                            ProductId = 34,
                            DescriptionProduct = "Description 34",
                            NameProduct = "Product34",
                            Price = 450
                        },
                        new
                        {
                            ProductId = 35,
                            DescriptionProduct = "Description 35",
                            NameProduct = "Product35",
                            Price = 185
                        },
                        new
                        {
                            ProductId = 36,
                            DescriptionProduct = "Description 36",
                            NameProduct = "Product36",
                            Price = 359
                        },
                        new
                        {
                            ProductId = 37,
                            DescriptionProduct = "Description 37",
                            NameProduct = "Product37",
                            Price = 462
                        },
                        new
                        {
                            ProductId = 38,
                            DescriptionProduct = "Description 38",
                            NameProduct = "Product38",
                            Price = 283
                        },
                        new
                        {
                            ProductId = 39,
                            DescriptionProduct = "Description 39",
                            NameProduct = "Product39",
                            Price = 467
                        },
                        new
                        {
                            ProductId = 40,
                            DescriptionProduct = "Description 40",
                            NameProduct = "Product40",
                            Price = 123
                        },
                        new
                        {
                            ProductId = 41,
                            DescriptionProduct = "Description 41",
                            NameProduct = "Product41",
                            Price = 272
                        },
                        new
                        {
                            ProductId = 42,
                            DescriptionProduct = "Description 42",
                            NameProduct = "Product42",
                            Price = 74
                        },
                        new
                        {
                            ProductId = 43,
                            DescriptionProduct = "Description 43",
                            NameProduct = "Product43",
                            Price = 204
                        },
                        new
                        {
                            ProductId = 44,
                            DescriptionProduct = "Description 44",
                            NameProduct = "Product44",
                            Price = 477
                        },
                        new
                        {
                            ProductId = 45,
                            DescriptionProduct = "Description 45",
                            NameProduct = "Product45",
                            Price = 98
                        },
                        new
                        {
                            ProductId = 46,
                            DescriptionProduct = "Description 46",
                            NameProduct = "Product46",
                            Price = 276
                        },
                        new
                        {
                            ProductId = 47,
                            DescriptionProduct = "Description 47",
                            NameProduct = "Product47",
                            Price = 405
                        },
                        new
                        {
                            ProductId = 48,
                            DescriptionProduct = "Description 48",
                            NameProduct = "Product48",
                            Price = 97
                        },
                        new
                        {
                            ProductId = 49,
                            DescriptionProduct = "Description 49",
                            NameProduct = "Product49",
                            Price = 328
                        },
                        new
                        {
                            ProductId = 50,
                            DescriptionProduct = "Description 50",
                            NameProduct = "Product50",
                            Price = 431
                        },
                        new
                        {
                            ProductId = 51,
                            DescriptionProduct = "Description 51",
                            NameProduct = "Product51",
                            Price = 444
                        },
                        new
                        {
                            ProductId = 52,
                            DescriptionProduct = "Description 52",
                            NameProduct = "Product52",
                            Price = 175
                        },
                        new
                        {
                            ProductId = 53,
                            DescriptionProduct = "Description 53",
                            NameProduct = "Product53",
                            Price = 121
                        },
                        new
                        {
                            ProductId = 54,
                            DescriptionProduct = "Description 54",
                            NameProduct = "Product54",
                            Price = 394
                        },
                        new
                        {
                            ProductId = 55,
                            DescriptionProduct = "Description 55",
                            NameProduct = "Product55",
                            Price = 451
                        },
                        new
                        {
                            ProductId = 56,
                            DescriptionProduct = "Description 56",
                            NameProduct = "Product56",
                            Price = 50
                        },
                        new
                        {
                            ProductId = 57,
                            DescriptionProduct = "Description 57",
                            NameProduct = "Product57",
                            Price = 271
                        },
                        new
                        {
                            ProductId = 58,
                            DescriptionProduct = "Description 58",
                            NameProduct = "Product58",
                            Price = 380
                        },
                        new
                        {
                            ProductId = 59,
                            DescriptionProduct = "Description 59",
                            NameProduct = "Product59",
                            Price = 442
                        },
                        new
                        {
                            ProductId = 60,
                            DescriptionProduct = "Description 60",
                            NameProduct = "Product60",
                            Price = 114
                        },
                        new
                        {
                            ProductId = 61,
                            DescriptionProduct = "Description 61",
                            NameProduct = "Product61",
                            Price = 384
                        },
                        new
                        {
                            ProductId = 62,
                            DescriptionProduct = "Description 62",
                            NameProduct = "Product62",
                            Price = 483
                        },
                        new
                        {
                            ProductId = 63,
                            DescriptionProduct = "Description 63",
                            NameProduct = "Product63",
                            Price = 45
                        },
                        new
                        {
                            ProductId = 64,
                            DescriptionProduct = "Description 64",
                            NameProduct = "Product64",
                            Price = 113
                        },
                        new
                        {
                            ProductId = 65,
                            DescriptionProduct = "Description 65",
                            NameProduct = "Product65",
                            Price = 79
                        },
                        new
                        {
                            ProductId = 66,
                            DescriptionProduct = "Description 66",
                            NameProduct = "Product66",
                            Price = 202
                        },
                        new
                        {
                            ProductId = 67,
                            DescriptionProduct = "Description 67",
                            NameProduct = "Product67",
                            Price = 52
                        },
                        new
                        {
                            ProductId = 68,
                            DescriptionProduct = "Description 68",
                            NameProduct = "Product68",
                            Price = 363
                        },
                        new
                        {
                            ProductId = 69,
                            DescriptionProduct = "Description 69",
                            NameProduct = "Product69",
                            Price = 50
                        },
                        new
                        {
                            ProductId = 70,
                            DescriptionProduct = "Description 70",
                            NameProduct = "Product70",
                            Price = 55
                        },
                        new
                        {
                            ProductId = 71,
                            DescriptionProduct = "Description 71",
                            NameProduct = "Product71",
                            Price = 118
                        },
                        new
                        {
                            ProductId = 72,
                            DescriptionProduct = "Description 72",
                            NameProduct = "Product72",
                            Price = 92
                        },
                        new
                        {
                            ProductId = 73,
                            DescriptionProduct = "Description 73",
                            NameProduct = "Product73",
                            Price = 273
                        },
                        new
                        {
                            ProductId = 74,
                            DescriptionProduct = "Description 74",
                            NameProduct = "Product74",
                            Price = 240
                        },
                        new
                        {
                            ProductId = 75,
                            DescriptionProduct = "Description 75",
                            NameProduct = "Product75",
                            Price = 489
                        },
                        new
                        {
                            ProductId = 76,
                            DescriptionProduct = "Description 76",
                            NameProduct = "Product76",
                            Price = 168
                        },
                        new
                        {
                            ProductId = 77,
                            DescriptionProduct = "Description 77",
                            NameProduct = "Product77",
                            Price = 485
                        },
                        new
                        {
                            ProductId = 78,
                            DescriptionProduct = "Description 78",
                            NameProduct = "Product78",
                            Price = 476
                        },
                        new
                        {
                            ProductId = 79,
                            DescriptionProduct = "Description 79",
                            NameProduct = "Product79",
                            Price = 59
                        },
                        new
                        {
                            ProductId = 80,
                            DescriptionProduct = "Description 80",
                            NameProduct = "Product80",
                            Price = 421
                        },
                        new
                        {
                            ProductId = 81,
                            DescriptionProduct = "Description 81",
                            NameProduct = "Product81",
                            Price = 20
                        },
                        new
                        {
                            ProductId = 82,
                            DescriptionProduct = "Description 82",
                            NameProduct = "Product82",
                            Price = 249
                        },
                        new
                        {
                            ProductId = 83,
                            DescriptionProduct = "Description 83",
                            NameProduct = "Product83",
                            Price = 236
                        },
                        new
                        {
                            ProductId = 84,
                            DescriptionProduct = "Description 84",
                            NameProduct = "Product84",
                            Price = 496
                        },
                        new
                        {
                            ProductId = 85,
                            DescriptionProduct = "Description 85",
                            NameProduct = "Product85",
                            Price = 237
                        },
                        new
                        {
                            ProductId = 86,
                            DescriptionProduct = "Description 86",
                            NameProduct = "Product86",
                            Price = 283
                        },
                        new
                        {
                            ProductId = 87,
                            DescriptionProduct = "Description 87",
                            NameProduct = "Product87",
                            Price = 230
                        },
                        new
                        {
                            ProductId = 88,
                            DescriptionProduct = "Description 88",
                            NameProduct = "Product88",
                            Price = 118
                        },
                        new
                        {
                            ProductId = 89,
                            DescriptionProduct = "Description 89",
                            NameProduct = "Product89",
                            Price = 499
                        },
                        new
                        {
                            ProductId = 90,
                            DescriptionProduct = "Description 90",
                            NameProduct = "Product90",
                            Price = 136
                        },
                        new
                        {
                            ProductId = 91,
                            DescriptionProduct = "Description 91",
                            NameProduct = "Product91",
                            Price = 89
                        },
                        new
                        {
                            ProductId = 92,
                            DescriptionProduct = "Description 92",
                            NameProduct = "Product92",
                            Price = 82
                        },
                        new
                        {
                            ProductId = 93,
                            DescriptionProduct = "Description 93",
                            NameProduct = "Product93",
                            Price = 341
                        },
                        new
                        {
                            ProductId = 94,
                            DescriptionProduct = "Description 94",
                            NameProduct = "Product94",
                            Price = 354
                        },
                        new
                        {
                            ProductId = 95,
                            DescriptionProduct = "Description 95",
                            NameProduct = "Product95",
                            Price = 239
                        },
                        new
                        {
                            ProductId = 96,
                            DescriptionProduct = "Description 96",
                            NameProduct = "Product96",
                            Price = 289
                        },
                        new
                        {
                            ProductId = 97,
                            DescriptionProduct = "Description 97",
                            NameProduct = "Product97",
                            Price = 29
                        },
                        new
                        {
                            ProductId = 98,
                            DescriptionProduct = "Description 98",
                            NameProduct = "Product98",
                            Price = 91
                        },
                        new
                        {
                            ProductId = 99,
                            DescriptionProduct = "Description 99",
                            NameProduct = "Product99",
                            Price = 398
                        });
                });

            modelBuilder.Entity("CatologDomain.ProductInStock", b =>
                {
                    b.Property<int>("ProductInStockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductInStockId");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            ProductInStockId = 1,
                            ProductId = 1,
                            Stock = 28
                        },
                        new
                        {
                            ProductInStockId = 2,
                            ProductId = 2,
                            Stock = 35
                        },
                        new
                        {
                            ProductInStockId = 3,
                            ProductId = 3,
                            Stock = 97
                        },
                        new
                        {
                            ProductInStockId = 4,
                            ProductId = 4,
                            Stock = 64
                        },
                        new
                        {
                            ProductInStockId = 5,
                            ProductId = 5,
                            Stock = 36
                        },
                        new
                        {
                            ProductInStockId = 6,
                            ProductId = 6,
                            Stock = 25
                        },
                        new
                        {
                            ProductInStockId = 7,
                            ProductId = 7,
                            Stock = 46
                        },
                        new
                        {
                            ProductInStockId = 8,
                            ProductId = 8,
                            Stock = 71
                        },
                        new
                        {
                            ProductInStockId = 9,
                            ProductId = 9,
                            Stock = 18
                        },
                        new
                        {
                            ProductInStockId = 10,
                            ProductId = 10,
                            Stock = 34
                        },
                        new
                        {
                            ProductInStockId = 11,
                            ProductId = 11,
                            Stock = 45
                        },
                        new
                        {
                            ProductInStockId = 12,
                            ProductId = 12,
                            Stock = 66
                        },
                        new
                        {
                            ProductInStockId = 13,
                            ProductId = 13,
                            Stock = 69
                        },
                        new
                        {
                            ProductInStockId = 14,
                            ProductId = 14,
                            Stock = 30
                        },
                        new
                        {
                            ProductInStockId = 15,
                            ProductId = 15,
                            Stock = 40
                        },
                        new
                        {
                            ProductInStockId = 16,
                            ProductId = 16,
                            Stock = 4
                        },
                        new
                        {
                            ProductInStockId = 17,
                            ProductId = 17,
                            Stock = 86
                        },
                        new
                        {
                            ProductInStockId = 18,
                            ProductId = 18,
                            Stock = 77
                        },
                        new
                        {
                            ProductInStockId = 19,
                            ProductId = 19,
                            Stock = 36
                        },
                        new
                        {
                            ProductInStockId = 20,
                            ProductId = 20,
                            Stock = 59
                        },
                        new
                        {
                            ProductInStockId = 21,
                            ProductId = 21,
                            Stock = 82
                        },
                        new
                        {
                            ProductInStockId = 22,
                            ProductId = 22,
                            Stock = 42
                        },
                        new
                        {
                            ProductInStockId = 23,
                            ProductId = 23,
                            Stock = 81
                        },
                        new
                        {
                            ProductInStockId = 24,
                            ProductId = 24,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 25,
                            ProductId = 25,
                            Stock = 59
                        },
                        new
                        {
                            ProductInStockId = 26,
                            ProductId = 26,
                            Stock = 61
                        },
                        new
                        {
                            ProductInStockId = 27,
                            ProductId = 27,
                            Stock = 4
                        },
                        new
                        {
                            ProductInStockId = 28,
                            ProductId = 28,
                            Stock = 4
                        },
                        new
                        {
                            ProductInStockId = 29,
                            ProductId = 29,
                            Stock = 91
                        },
                        new
                        {
                            ProductInStockId = 30,
                            ProductId = 30,
                            Stock = 84
                        },
                        new
                        {
                            ProductInStockId = 31,
                            ProductId = 31,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 32,
                            ProductId = 32,
                            Stock = 21
                        },
                        new
                        {
                            ProductInStockId = 33,
                            ProductId = 33,
                            Stock = 92
                        },
                        new
                        {
                            ProductInStockId = 34,
                            ProductId = 34,
                            Stock = 61
                        },
                        new
                        {
                            ProductInStockId = 35,
                            ProductId = 35,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 36,
                            ProductId = 36,
                            Stock = 86
                        },
                        new
                        {
                            ProductInStockId = 37,
                            ProductId = 37,
                            Stock = 99
                        },
                        new
                        {
                            ProductInStockId = 38,
                            ProductId = 38,
                            Stock = 57
                        },
                        new
                        {
                            ProductInStockId = 39,
                            ProductId = 39,
                            Stock = 24
                        },
                        new
                        {
                            ProductInStockId = 40,
                            ProductId = 40,
                            Stock = 73
                        },
                        new
                        {
                            ProductInStockId = 41,
                            ProductId = 41,
                            Stock = 40
                        },
                        new
                        {
                            ProductInStockId = 42,
                            ProductId = 42,
                            Stock = 57
                        },
                        new
                        {
                            ProductInStockId = 43,
                            ProductId = 43,
                            Stock = 51
                        },
                        new
                        {
                            ProductInStockId = 44,
                            ProductId = 44,
                            Stock = 54
                        },
                        new
                        {
                            ProductInStockId = 45,
                            ProductId = 45,
                            Stock = 71
                        },
                        new
                        {
                            ProductInStockId = 46,
                            ProductId = 46,
                            Stock = 37
                        },
                        new
                        {
                            ProductInStockId = 47,
                            ProductId = 47,
                            Stock = 93
                        },
                        new
                        {
                            ProductInStockId = 48,
                            ProductId = 48,
                            Stock = 85
                        },
                        new
                        {
                            ProductInStockId = 49,
                            ProductId = 49,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 50,
                            ProductId = 50,
                            Stock = 97
                        },
                        new
                        {
                            ProductInStockId = 51,
                            ProductId = 51,
                            Stock = 5
                        },
                        new
                        {
                            ProductInStockId = 52,
                            ProductId = 52,
                            Stock = 30
                        },
                        new
                        {
                            ProductInStockId = 53,
                            ProductId = 53,
                            Stock = 89
                        },
                        new
                        {
                            ProductInStockId = 54,
                            ProductId = 54,
                            Stock = 19
                        },
                        new
                        {
                            ProductInStockId = 55,
                            ProductId = 55,
                            Stock = 69
                        },
                        new
                        {
                            ProductInStockId = 56,
                            ProductId = 56,
                            Stock = 86
                        },
                        new
                        {
                            ProductInStockId = 57,
                            ProductId = 57,
                            Stock = 53
                        },
                        new
                        {
                            ProductInStockId = 58,
                            ProductId = 58,
                            Stock = 82
                        },
                        new
                        {
                            ProductInStockId = 59,
                            ProductId = 59,
                            Stock = 4
                        },
                        new
                        {
                            ProductInStockId = 60,
                            ProductId = 60,
                            Stock = 75
                        },
                        new
                        {
                            ProductInStockId = 61,
                            ProductId = 61,
                            Stock = 21
                        },
                        new
                        {
                            ProductInStockId = 62,
                            ProductId = 62,
                            Stock = 41
                        },
                        new
                        {
                            ProductInStockId = 63,
                            ProductId = 63,
                            Stock = 80
                        },
                        new
                        {
                            ProductInStockId = 64,
                            ProductId = 64,
                            Stock = 33
                        },
                        new
                        {
                            ProductInStockId = 65,
                            ProductId = 65,
                            Stock = 30
                        },
                        new
                        {
                            ProductInStockId = 66,
                            ProductId = 66,
                            Stock = 23
                        },
                        new
                        {
                            ProductInStockId = 67,
                            ProductId = 67,
                            Stock = 74
                        },
                        new
                        {
                            ProductInStockId = 68,
                            ProductId = 68,
                            Stock = 7
                        },
                        new
                        {
                            ProductInStockId = 69,
                            ProductId = 69,
                            Stock = 26
                        },
                        new
                        {
                            ProductInStockId = 70,
                            ProductId = 70,
                            Stock = 54
                        },
                        new
                        {
                            ProductInStockId = 71,
                            ProductId = 71,
                            Stock = 5
                        },
                        new
                        {
                            ProductInStockId = 72,
                            ProductId = 72,
                            Stock = 28
                        },
                        new
                        {
                            ProductInStockId = 73,
                            ProductId = 73,
                            Stock = 52
                        },
                        new
                        {
                            ProductInStockId = 74,
                            ProductId = 74,
                            Stock = 62
                        },
                        new
                        {
                            ProductInStockId = 75,
                            ProductId = 75,
                            Stock = 18
                        },
                        new
                        {
                            ProductInStockId = 76,
                            ProductId = 76,
                            Stock = 25
                        },
                        new
                        {
                            ProductInStockId = 77,
                            ProductId = 77,
                            Stock = 90
                        },
                        new
                        {
                            ProductInStockId = 78,
                            ProductId = 78,
                            Stock = 26
                        },
                        new
                        {
                            ProductInStockId = 79,
                            ProductId = 79,
                            Stock = 43
                        },
                        new
                        {
                            ProductInStockId = 80,
                            ProductId = 80,
                            Stock = 22
                        },
                        new
                        {
                            ProductInStockId = 81,
                            ProductId = 81,
                            Stock = 67
                        },
                        new
                        {
                            ProductInStockId = 82,
                            ProductId = 82,
                            Stock = 18
                        },
                        new
                        {
                            ProductInStockId = 83,
                            ProductId = 83,
                            Stock = 89
                        },
                        new
                        {
                            ProductInStockId = 84,
                            ProductId = 84,
                            Stock = 93
                        },
                        new
                        {
                            ProductInStockId = 85,
                            ProductId = 85,
                            Stock = 79
                        },
                        new
                        {
                            ProductInStockId = 86,
                            ProductId = 86,
                            Stock = 73
                        },
                        new
                        {
                            ProductInStockId = 87,
                            ProductId = 87,
                            Stock = 32
                        },
                        new
                        {
                            ProductInStockId = 88,
                            ProductId = 88,
                            Stock = 72
                        },
                        new
                        {
                            ProductInStockId = 89,
                            ProductId = 89,
                            Stock = 92
                        },
                        new
                        {
                            ProductInStockId = 90,
                            ProductId = 90,
                            Stock = 17
                        },
                        new
                        {
                            ProductInStockId = 91,
                            ProductId = 91,
                            Stock = 32
                        },
                        new
                        {
                            ProductInStockId = 92,
                            ProductId = 92,
                            Stock = 16
                        },
                        new
                        {
                            ProductInStockId = 93,
                            ProductId = 93,
                            Stock = 53
                        },
                        new
                        {
                            ProductInStockId = 94,
                            ProductId = 94,
                            Stock = 48
                        },
                        new
                        {
                            ProductInStockId = 95,
                            ProductId = 95,
                            Stock = 52
                        },
                        new
                        {
                            ProductInStockId = 96,
                            ProductId = 96,
                            Stock = 98
                        },
                        new
                        {
                            ProductInStockId = 97,
                            ProductId = 97,
                            Stock = 77
                        },
                        new
                        {
                            ProductInStockId = 98,
                            ProductId = 98,
                            Stock = 18
                        },
                        new
                        {
                            ProductInStockId = 99,
                            ProductId = 99,
                            Stock = 24
                        });
                });

            modelBuilder.Entity("CatologDomain.ProductInStock", b =>
                {
                    b.HasOne("CatologDomain.Product", null)
                        .WithOne("stock")
                        .HasForeignKey("CatologDomain.ProductInStock", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
